module.exports = {
    en: {
        suggestion_footer: "Suggestion System",
        suggestion_accepted: "✅ Accepted",
        suggestion_rejected: "❌ Rejected",
        suggestion_accepted_by: "Accepted by",
        suggestion_rejected_by: "Rejected by",
        suggestion_dm_accepted: "✅ Your suggestion has been accepted!",
        suggestion_dm_rejected: "❌ Your suggestion was rejected.",
        suggestion_reason: "Reason",
        feedback_footer: "Feedback System",
        feedback_rating_title: "Rating",
        feedback_prompt: "please select a rating for your feedback:",
        feedback_from: "Feedback from",
        ai_error_no_key: "⚠️ **AI Error**: No API Key configured. Please check your dashboard.",
        ai_error_server: "❌ **AI Error**: Server returned status",
        ai_error_invalid: "⚠️ **AI Error**: The AI didn't return a valid response.",
        ai_error_connect: "❌ **Connection Error**: I couldn't reach the AI server. Please try again later.",
        btn_accept: "Accept",
        btn_reject: "Reject",
        cmd_ban_success: "✅ **{user}** has been banned.",
        cmd_ban_usage: "Please mention a user to ban.",
        cmd_kick_success: "✅ **{user}** has been kicked.",
        cmd_kick_usage: "Please mention a user to kick.",
        cmd_clear_success: "Deleted {amount} messages.",
        cmd_clear_usage: "Please provide a number between 1 and 100.",
        cmd_lock: "🔒 Channel locked.",
        cmd_unlock: "🔓 Channel unlocked.",
        cmd_timeout_success: "✅ **{user}** acted timed out for {time} minutes.",
        cmd_timeout_usage: "Usage: !timeout @user <minutes> [reason]",
        cmd_untimeout_success: "✅ Timeout removed for **{user}**.",
        cmd_role_add: "Added **{role}** to **{user}**.",
        cmd_role_remove: "Removed **{role}** from **{user}**.",
        cmd_role_usage: "Usage: !role @user @role",
        cmd_hide: "🙈 Channel hidden.",
        cmd_show: "👁️ Channel visible.",
        cmd_nick_success: "Updated nickname for **{user}**.",
        cmd_nick_usage: "Usage: !nick @user <new nickname>",
        cmd_jail_success: "✅ **{user}** has been jailed for {time}.",
        cmd_jail_usage: "Usage: !jail @user <duration> [reason]\\nExample: !jail @user 10m Bad behavior",
        cmd_unjail_success: "✅ **{user}** has been unjailed.",
        cmd_unjail_usage: "Usage: !unjail @user",
        cmd_error: "An error occurred while executing the command."
    },
    ar: {
        suggestion_footer: "نظام الاقتراحات",
        suggestion_accepted: "✅ تم القبول",
        suggestion_rejected: "❌ تم الرفض",
        suggestion_accepted_by: "تم القبول بواسطة",
        suggestion_rejected_by: "تم الرفض بواسطة",
        suggestion_dm_accepted: "✅ تم قبول اقتراحك!",
        suggestion_dm_rejected: "❌ تم رفض اقتراحك.",
        suggestion_reason: "السبب",
        feedback_footer: "نظام الآراء",
        feedback_rating_title: "التقييم",
        feedback_prompt: "يرجى تحديد تقييم لملاحظاتك:",
        feedback_from: "رأي من",
        ai_error_no_key: "⚠️ **خطأ AI**: لم يتم تكوين مفتاح API. يرجى مراجعة لوحة التحكم.",
        ai_error_server: "❌ **خطأ AI**: الخادم ارجع حالة",
        ai_error_invalid: "⚠️ **خطأ AI**: لم يرجع الذكاء الاصطناعي استجابة صالحة.",
        ai_error_connect: "❌ **خطأ في الاتصال**: لم أتمكن من الوصول إلى خادم AI. حاول مرة أخرى لاحقًا.",
        btn_accept: "قبول",
        btn_reject: "رفض",
        cmd_ban_success: "✅ تم حظر **{user}** بنجاح.",
        cmd_ban_usage: "يرجى منشن المستخدم للحظر.",
        cmd_kick_success: "✅ تم طرد **{user}** بنجاح.",
        cmd_kick_usage: "يرجى منشن المستخدم للطرد.",
        cmd_clear_success: "تم حذف {amount} رسالة.",
        cmd_clear_usage: "يرجى توفير رقم بين 1 و 100.",
        cmd_lock: "🔒 تم إغلاق القناة.",
        cmd_unlock: "🔓 تم فتح القناة.",
        cmd_timeout_success: "✅ تم إسكات **{user}** لمدة {time} دقائق.",
        cmd_timeout_usage: "الاستخدام: !timeout @user <minutes> [السبب]",
        cmd_untimeout_success: "✅ تم إزالة الإسكات عن **{user}**.",
        cmd_role_add: "تم إعطاء رتبة **{role}** لـ {user}.",
        cmd_role_remove: "تم سحب رتبة **{role}** من {user}.",
        cmd_role_usage: "الاستخدام: !role @user @role",
        cmd_hide: "🙈 تم إخفاء القناة.",
        cmd_show: "👁️ تم إظهار القناة.",
        cmd_nick_success: "تم تحديث اسم **{user}**.",
        cmd_nick_usage: "الاستخدام: !nick @user <new nickname>",
        cmd_jail_success: "✅ تم سجن **{user}** لمدة {time}.",
        cmd_jail_usage: "الاستخدام: !jail @user <duration> [reason]\\nمثال: !jail @user 10m Bad behavior",
        cmd_unjail_success: "✅ تم فك سجن **{user}**.",
        cmd_unjail_usage: "الاستخدام: !unjail @user",
        cmd_error: "حدث خطأ أثناء تنفيذ الأمر."
    }
};
